export declare const FEATURE_FLAGS: {
    readonly "protection.enabled": true;
    readonly "protection.auto_checkpoint": true;
    readonly "protection.pre_save_hook": true;
    readonly "risk.guardian_v2": false;
    readonly "risk.dependency_analysis": true;
    readonly "risk.deep_analysis": false;
    readonly "risk.ai_detection": true;
    readonly "storage.compression": true;
    readonly "storage.deduplication": false;
    readonly "storage.encryption": false;
    readonly "ui.chat_participant": true;
    readonly "ui.status_bar": true;
    readonly "ui.timeline_view": true;
    readonly "telemetry.detailed_events": false;
    readonly "telemetry.performance_metrics": true;
    readonly "telemetry.sampling_rate": 1;
    readonly "experimental.mcp_tools": false;
    readonly "experimental.recovery_mode": false;
};
export type FeatureFlag = keyof typeof FEATURE_FLAGS;
