import { defineConfig } from "tsup";

export default defineConfig({
	entry: [
		"src/index.ts",
		"src/client/client.ts",
		"src/client/middleware.ts",
		"src/client/server.ts",
		"src/client/types.ts",
		"src/db/client.ts",
		"src/db/database-service.ts",
		"src/db/supabase-service.ts",
		"src/db/test-utils.ts",
		"src/db/queries/index.ts",
		"src/db/zod.ts",
		"src/db/schema/postgres.ts",
		"src/db/schema/snapback/index.ts",
		"src/db/schema/extension-auth.ts",
		"src/db/adapters/TelemetrySinkDb.ts",
	],
	format: ["esm"],
	dts: { resolve: true },
	clean: true,
	sourcemap: true,
	outDir: "dist",
	splitting: false,
	treeshake: true,
	tsconfig: "tsconfig.json",
	target: "es2022",
	external: ["next", "next/*", "next/headers", "next/server", "next/navigation"],
});
