export { type AuthResult, createDeviceAuthClient, DeviceAuthClient, type DeviceAuthCallbacks, type DeviceAuthClientConfig, type DeviceAuthError, type DeviceAuthErrorResponse, type DeviceCodeResponse, type FlowState, type TokenResponse, } from "./auth/DeviceAuthClient";
export { createChangeSummary, type FileChange, FileChangeAnalyzer, type FileChangeType, type IFileSystemProvider as IFileSystemProviderAnalysis, } from "./analysis/FileChangeAnalyzer";
export { type AnalysisResult, DEFAULT_RISK_THRESHOLDS, RiskAnalyzer, type RiskFactor, type RiskSeverity, } from "./analysis/RiskAnalyzer";
export * from "./cache/lru-cache";
export { type Envelope, SnapbackAnalyticsClient, SnapbackClient } from "./client";
export { ProtectionClient } from "./client/ProtectionClient";
export { SnapshotClient } from "./client/SnapshotClient";
export { type CloudBackupConfig, CloudBackupService, type DownloadResult, type UploadResult, } from "./cloud/CloudBackupService";
export * from "./config";
export { type ConfigChange, ConfigDetector, type ConfigDetectorOptions, type ConfigFile, type ConfigParseResult, type ConfigValidationResult, type IFileSystemProvider, } from "./config/ConfigDetector";
export { type MergeOptions, type ParseResult, SnapBackRCParser } from "./config/SnapBackRCParser";
export { type BurstThresholds, createThresholds, DEFAULT_THRESHOLDS, type DetectionThresholds, type ExperienceThresholds, type ProtectionThresholds, type QoSThresholds, type ResourceThresholds, type RiskThresholds, resetThresholds, type SecurityPatternScores, type SessionThresholds, type TaggingThresholds, THRESHOLDS, type ThresholdsConfig, updateThresholds, } from "./config/Thresholds";
export type { ProtectionLevel, ProtectionRule, SnapBackHooks, SnapBackPolicies, SnapBackRC, SnapBackSettings, SnapshotTemplate, } from "./config/types";
export { AI_EXTENSION_IDS, type AIAssistantName, AIPresenceDetector, type IExtensionProvider, } from "./core/detection/AIPresenceDetector";
export { type BurstDetectionResult, type BurstDetectorConfig, BurstHeuristicsDetector, } from "./core/detection/BurstHeuristicsDetector";
export { CursorDetector, type IEnvironmentProvider, } from "./core/detection/CursorDetector";
export { DEFAULT_EXPERIENCE_THRESHOLDS, ExperienceClassifier, type ExperienceClassifierOptions, type ExperienceThresholdsConfig, type ExperienceTier, type IKeyValueStorage, } from "./core/session/ExperienceClassifier";
export { type IDisposable, type IEventEmitter, type ILogger, type ISessionStorage, type ITimerService, NodeTimerService, NoOpLogger, } from "./core/session/interfaces";
export { SessionCoordinator, type SessionCoordinatorConfig, type SessionCoordinatorOptions, } from "./core/session/SessionCoordinator";
export { type ISnapshotProvider, SessionSummaryGenerator, type SessionSummaryGeneratorOptions, } from "./core/session/SessionSummaryGenerator";
export { type AIPresenceInfo, type SessionTag, SessionTagger, type SessionTaggerConfig, type SessionTaggerOptions, type SessionTaggingResult, } from "./core/session/SessionTagger";
export type { SessionCandidate, SessionFileEntry, SessionFinalizeReason, SessionId, SessionManifest, } from "./core/session/types";
export { EncryptionService } from "./encryption/EncryptionService";
export { ApiError, AuthenticationError, AuthorizationError, ensureSnapBackError, InputValidationError, isApiError, isRetryableError, isSnapBackError, isSnapshotError, isStorageError, isValidationError, MissingContentError, PathValidationError, RateLimitError, SnapBackError, SnapshotCreationError, SnapshotDuplicateError, SnapshotError, SnapshotNotFoundError, SnapshotProtectedError, SnapshotRestoreError, SnapshotVerificationError, SnapshotVersionError, StorageError as SnapBackStorageError, StorageFullError as SnapBackStorageFullError, StorageIOError, StorageLockError as SnapBackStorageLockError, toError as toSnapBackError, ValidationError, } from "./errors";
export { type AtomicWriteOptions, atomicWriteFile, atomicWriteFileSync, DEFAULT_MAX_SIZE, } from "./fs/atomic";
export { analyze, evaluatePolicy, ingestTelemetry } from "./helpers";
export * from "./privacy/hasher";
export * from "./privacy/sanitizer";
export * from "./privacy/validator";
export { ProtectionManager } from "./protection/ProtectionManager";
export { Snapback } from "./Snapback";
export * from "./session/index";
export { applyAutomaticFix, createSnapshotWithRetry, createSnapshotWithRetrySafe, type DiagnosisType, diagnoseSnapshotFailure, formatDiagnosis, type RetryConfig, type SnapshotDiagnosis, type SnapshotParams, type SnapshotRetryResult, } from "./snapshot/retry-hook";
export { SnapshotManager } from "./snapshot/SnapshotManager";
export { type FileChange as SnapshotFileChange, type SnapshotInfo, SnapshotNamingStrategy, type SnapshotNamingStrategyOptions, } from "./snapshot/SnapshotNamingStrategy";
export { type ConflictResult, FileConflictResolver, type FileConflictResolverOptions, type IFileSearchProvider, type RestoreMetadata, } from "./snapshot/FileConflictResolver";
export { type IconResult, type SnapshotMetadata, SnapshotIconStrategy, } from "./snapshot/SnapshotIconStrategy";
export { type AutoCleanupConfig, type DeletableSnapshot, type DeletionOptions, type DeletionResult, type IConfirmationService, type ISnapshotManagerForDeletion, SnapshotDeletionService, type SnapshotDeletionServiceOptions, } from "./snapshot/SnapshotDeletionService";
export { LocalStorage } from "./storage/LocalStorage";
export { MemoryStorage } from "./storage/MemoryStorage";
export type { StorageAdapter } from "./storage/StorageAdapter";
export { StorageBroker } from "./storage/StorageBroker";
export { StorageBrokerAdapter } from "./storage/StorageBrokerAdapter";
export { CorruptedDataError, StorageConnectionError, StorageError, StorageFullError, StorageLockError, } from "./storage/StorageErrors";
export type { SDKConfig } from "./types";
export type { ExperienceMetrics } from "./types/experience";
export { toError } from "./utils/errorHelpers";
export { getBlobPath, hashContent, hashFilePath, hashWorkspaceId, sha256 } from "./utils/hash";
export { generateAuditId, generateCheckpointId, generateId, generateSessionId, generateSnapshotId, ID_PREFIX, type IdPrefix, isValidId, parseIdPrefix, parseIdTimestamp, randomId, type SnapshotId, } from "./utils/id-generation";
export { areEqual, getDepth, isWithin, normalize } from "./utils/PathNormalizer";
export { all, allOrErrors, andThen, err, fromPromise, fromPromiseWith, isErr, isOk, map, mapErr, match, ok, type Result, sequence, tap, tapErr, toPromise, tryAll, tryCatch, tryCatchAsync, unwrap, unwrapOr, unwrapOrElse, } from "./utils/result";
export { calculateBackoff, type RetryOptions, RetryPresets, withRetry } from "./utils/retry";
export * from "./arch/index";
//# sourceMappingURL=index.d.ts.map