/**
 * Unit tests for AIDetector
 * L1: Pure logic - detects AI patterns in diffs without VS Code runtime
 */

import { beforeEach, describe, expect, it, vi } from "vitest";

// ============================================
// Types
// ============================================

interface AIDetectionResult {
	detected: boolean;
	tool: "cursor" | "copilot" | "claude" | "unknown" | null;
	confidence: number; // 0-1
	patterns: string[];
	isBurst: boolean;
}

interface BurstConfig {
	minChanges: number;
	windowMs: number;
	minCharsPerChange: number;
}

// ============================================
// Implementation (would be in src/detection/AIDetector.ts)
// ============================================

class AIDetector {
	private static readonly PATTERNS = {
		cursor: [/\/\/ Generated by Cursor/i, /Cursor:\s*\w+/, /@cursor-ai/i],
		copilot: [/GitHub Copilot/i, /Copilot suggestion/i, /\/\/ copilot:/i],
		claude: [/Generated by Claude/i, /Anthropic/i, /\/\/ Claude:/i],
	};

	private burstConfig: BurstConfig = {
		minChanges: 5,
		windowMs: 30_000, // 30 seconds
		minCharsPerChange: 50,
	};

	private changeHistory: { timestamp: number; chars: number }[] = [];

	constructor(config?: Partial<BurstConfig>) {
		if (config) {
			this.burstConfig = { ...this.burstConfig, ...config };
		}
	}

	/**
	 * Analyze a diff string for AI patterns
	 */
	analyze(diff: string): AIDetectionResult {
		const patterns: string[] = [];
		let tool: AIDetectionResult["tool"] = null;
		let confidence = 0;

		// Check for tool-specific patterns
		for (const [toolName, toolPatterns] of Object.entries(AIDetector.PATTERNS)) {
			for (const pattern of toolPatterns) {
				if (pattern.test(diff)) {
					patterns.push(pattern.source);
					tool = toolName as AIDetectionResult["tool"];
					confidence = Math.max(confidence, 0.9);
				}
			}
		}

		// Heuristic: Large additions with consistent formatting
		const addedLines = diff.split("\n").filter((line) => line.startsWith("+"));
		if (addedLines.length > 10) {
			// Check for consistent indentation (AI tends to be very consistent)
			const indentations = addedLines.map((line) => {
				const match = line.match(/^\+(\s*)/);
				return match ? match[1].length : 0;
			});
			const uniqueIndents = new Set(indentations);
			if (uniqueIndents.size <= 3) {
				confidence = Math.max(confidence, 0.6);
				patterns.push("consistent-formatting");
			}
		}

		// Check for burst editing
		const isBurst = this.checkBurst(diff.length);
		if (isBurst) {
			confidence = Math.max(confidence, 0.7);
			patterns.push("burst-edit");
		}

		return {
			detected: confidence >= 0.5,
			tool: confidence >= 0.5 ? (tool ?? "unknown") : null,
			confidence,
			patterns,
			isBurst,
		};
	}

	/**
	 * Record a change and check if we're in a burst
	 */
	checkBurst(chars: number): boolean {
		const now = Date.now();

		// Add current change
		this.changeHistory.push({ timestamp: now, chars });

		// Clean old entries outside window
		this.changeHistory = this.changeHistory.filter((entry) => now - entry.timestamp <= this.burstConfig.windowMs);

		// Check burst conditions
		const significantChanges = this.changeHistory.filter(
			(entry) => entry.chars >= this.burstConfig.minCharsPerChange,
		);

		return significantChanges.length >= this.burstConfig.minChanges;
	}

	/**
	 * Reset burst history
	 */
	resetBurstHistory(): void {
		this.changeHistory = [];
	}

	/**
	 * Detect tool from content only (no burst consideration)
	 */
	detectTool(content: string): AIDetectionResult["tool"] {
		for (const [toolName, toolPatterns] of Object.entries(AIDetector.PATTERNS)) {
			for (const pattern of toolPatterns) {
				if (pattern.test(content)) {
					return toolName as AIDetectionResult["tool"];
				}
			}
		}
		return null;
	}
}

// ============================================
// TESTS
// ============================================

describe("AIDetector", () => {
	let detector: AIDetector;

	beforeEach(() => {
		vi.useFakeTimers();
		detector = new AIDetector({
			minChanges: 5,
			windowMs: 30_000,
			minCharsPerChange: 50,
		});
	});

	afterEach(() => {
		vi.useRealTimers();
	});

	describe("Pattern Detection", () => {
		it("detects Cursor patterns in diff", () => {
			const diff = `
+// Generated by Cursor
+function hello() {
+  console.log("hello");
+}
      `;

			const result = detector.analyze(diff);

			expect(result.detected).toBe(true);
			expect(result.tool).toBe("cursor");
			expect(result.confidence).toBeGreaterThanOrEqual(0.9);
			expect(result.patterns).toContain(/\/\/ Generated by Cursor/i.source);
		});

		it("detects Copilot patterns in diff", () => {
			const diff = `
+// GitHub Copilot suggestion
+const utils = {
+  format: (str) => str.trim()
+};
      `;

			const result = detector.analyze(diff);

			expect(result.detected).toBe(true);
			expect(result.tool).toBe("copilot");
			expect(result.confidence).toBeGreaterThanOrEqual(0.9);
		});

		it("detects Claude patterns in diff", () => {
			const diff = `
+// Generated by Claude
+interface User {
+  id: string;
+  name: string;
+}
      `;

			const result = detector.analyze(diff);

			expect(result.detected).toBe(true);
			expect(result.tool).toBe("claude");
		});

		it("returns unknown for ambiguous patterns", () => {
			const diff = `
+function processData(data) {
+  return data.map(item => item.value);
+}
      `;

			const result = detector.analyze(diff);

			// Low confidence, no specific tool
			expect(result.tool).toBeNull();
			expect(result.confidence).toBeLessThan(0.5);
		});

		it("handles empty diff", () => {
			const result = detector.analyze("");

			expect(result.detected).toBe(false);
			expect(result.tool).toBeNull();
			expect(result.confidence).toBe(0);
		});

		it("handles null-like input gracefully", () => {
			// @ts-expect-error Testing edge case
			expect(() => detector.analyze(null)).not.toThrow();
		});
	});

	describe("Burst Detection", () => {
		it("triggers burst on 5+ saves with >50 chars in 30 seconds", () => {
			// Simulate 5 rapid edits
			for (let i = 0; i < 5; i++) {
				const result = detector.checkBurst(100); // 100 chars each
				if (i < 4) {
					expect(result).toBe(false);
				} else {
					expect(result).toBe(true);
				}
				vi.advanceTimersByTime(1000); // 1 second between edits
			}
		});

		it("does not trigger on small changes", () => {
			// 10 small edits (< 50 chars)
			for (let i = 0; i < 10; i++) {
				const result = detector.checkBurst(30);
				expect(result).toBe(false);
				vi.advanceTimersByTime(1000);
			}
		});

		it("resets window after timeout", () => {
			// 4 edits (not enough)
			for (let i = 0; i < 4; i++) {
				detector.checkBurst(100);
				vi.advanceTimersByTime(1000);
			}

			// Wait for window to expire
			vi.advanceTimersByTime(35_000);

			// Next edit starts fresh
			const result = detector.checkBurst(100);
			expect(result).toBe(false);
		});

		it("tracks per-file independently via separate instances", () => {
			const detector1 = new AIDetector();
			const detector2 = new AIDetector();

			// Burst on detector1
			for (let i = 0; i < 5; i++) {
				detector1.checkBurst(100);
			}

			// detector2 should not be in burst
			expect(detector2.checkBurst(100)).toBe(false);
		});

		it("resets burst history on demand", () => {
			// Build up history
			for (let i = 0; i < 4; i++) {
				detector.checkBurst(100);
			}

			detector.resetBurstHistory();

			// Should start fresh
			expect(detector.checkBurst(100)).toBe(false);
		});
	});

	describe("Combined Analysis", () => {
		it("increases confidence when burst + pattern detected", () => {
			// Build up burst
			for (let i = 0; i < 4; i++) {
				detector.checkBurst(100);
				vi.advanceTimersByTime(1000);
			}

			// Now analyze with pattern
			const result = detector.analyze(`
+// Generated by Cursor
+${"x".repeat(100)}
      `);

			expect(result.detected).toBe(true);
			expect(result.isBurst).toBe(true);
			expect(result.confidence).toBeGreaterThanOrEqual(0.9);
			expect(result.patterns).toContain("burst-edit");
		});

		it("detects AI via formatting heuristics", () => {
			// Large, consistently formatted addition (no explicit marker)
			const lines = Array(15).fill('+  console.log("line");').join("\n");

			const result = detector.analyze(lines);

			expect(result.patterns).toContain("consistent-formatting");
			expect(result.confidence).toBeGreaterThanOrEqual(0.6);
		});
	});

	describe("Confidence Scoring", () => {
		it("returns confidence between 0 and 1", () => {
			const testCases = ["", "normal code", "// Generated by Cursor", "+".repeat(1000)];

			for (const input of testCases) {
				const result = detector.analyze(input);
				expect(result.confidence).toBeGreaterThanOrEqual(0);
				expect(result.confidence).toBeLessThanOrEqual(1);
			}
		});

		it("threshold of 0.5 determines detected flag", () => {
			const lowConfidence = detector.analyze("minor change");
			expect(lowConfidence.detected).toBe(false);

			const highConfidence = detector.analyze("// Generated by Cursor\n+code");
			expect(highConfidence.detected).toBe(true);
		});
	});

	describe("Tool Detection (Direct)", () => {
		it("detectTool returns tool name for matching content", () => {
			expect(detector.detectTool("GitHub Copilot")).toBe("copilot");
			expect(detector.detectTool("Generated by Claude")).toBe("claude");
			expect(detector.detectTool("// cursor-ai")).toBe("cursor");
		});

		it("detectTool returns null for no match", () => {
			expect(detector.detectTool("function foo() {}")).toBeNull();
		});
	});
});
