import { defineConfig } from "tsup";

export default defineConfig({
	entry: {
		index: "src/index.ts",
		"vitals/index": "src/vitals/index.ts",
		"motion/index": "src/motion/index.ts",
	},
	format: ["esm"],
	dts: false, // Types generated by tsc via tsconfig composite
	sourcemap: true,
	clean: true,
	external: ["react", "react-dom", "motion"],
	treeshake: true,
	splitting: false,
	skipNodeModulesBundle: true,
	// Preserve RSC directive - motion utils require "use client"
	esbuildOptions(opts) {
		opts.banner = {
			js: '"use client";',
		};
	},
});
